services:
  - type: web
    name: shl-assessment-agent
    env: docker
    region: ohio
    plan: free
    branch: main
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: PORT
        value: 8000
      - key: HF_HOME
        value: /app/.hf_cache
